development:
  adapter: postgresql
  encoding: unicode
  database: crud_app_development
  pool: 5
  username: user
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: crud_app_test
  pool: 5
  username: user
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: d5mv8p5k9gltps
  pool: 5
  username: jpvnxybjxsgumf
  password: PW7-oDVbkgpD9bigad6flh0-K_
  host: ec2-23-23-243-111.compute-1.amazonaws.com
